version: '3'

services:
  traefik:
    image: traefik:v2.10
    container_name: appwrite-traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - appwrite-letsencrypt:/letsencrypt
    networks:
      - appwrite

  appwrite:
    image: appwrite/appwrite:1.4.11
    container_name: appwrite
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - appwrite-uploads:/storage/uploads:rw
      - appwrite-cache:/storage/cache:rw
      - appwrite-config:/storage/config:rw
      - appwrite-certificates:/storage/certificates:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.appwrite.rule=Host(`localhost`)
      - traefik.http.routers.appwrite.entrypoints=web
      - traefik.http.services.appwrite.loadbalancer.server.port=80
    environment:
      - APPWRITE_HTTP_PORT=80
      - APPWRITE_REDIS_PORT=6379
      - APPWRITE_REDIS_USER=
      - APPWRITE_REDIS_PASS=
      - APPWRITE_DB_PORT=3306
      - APPWRITE_DB_USER=root
      - APPWRITE_DB_PASS=password
      - APPWRITE_DB_NAME=appwrite
      - APPWRITE_SMTP_HOST=
      - APPWRITE_SMTP_PORT=
      - APPWRITE_SMTP_USER=
      - APPWRITE_SMTP_PASS=
      - APPWRITE_LOCALE=en
      - APPWRITE_DOMAIN=localhost
      - APPWRITE_DOMAIN_TARGET=localhost
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb:10.7
    container_name: appwrite-mariadb
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - appwrite-mariadb:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=appwrite
    command: --innodb-flush-method=fsync

  redis:
    image: redis:7.0
    container_name: appwrite-redis
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - appwrite-redis:/data:rw

networks:
  appwrite:
    name: appwrite
    attachable: true

volumes:
  appwrite-mariadb:
  appwrite-redis:
  appwrite-cache:
  appwrite-uploads:
  appwrite-config:
  appwrite-certificates:
  appwrite-letsencrypt: